site:
  about:
    siteName: Orchid
    siteDescription: Build and deploy beautiful, organic, modular static sites
    avatar: 'assets/media/avatar.jpg'

theme:
  social:
    other:
      - link: '/'
        label: 'Home'
        icon: 'fas fa-home'
      - link: 'https://github.com/JavaEden/Orchid'
        label: 'Github'
        icon: 'fab fa-github'
      - link: 'https://twitter.com/OrchidSSG'
        label: 'Twitter'
        icon: 'fab fa-twitter'
  primaryColor: '#7E80CF'
  bannerColor: '#444444'
  linkColor: '#7E80CF'
  trianglifyOptions:
    x_colors: 'BuPu'
    cell_size: 55
    seed: 1
  menu:
    - type: 'page'
      itemId: 'Quick-Start'
      title: 'Get Started'
    - type: 'wikiSections'
    - type: 'taxonomy'
      taxonomyType: 'group'
      includeTerms: false
      title: 'Plugins and Themes'
  sidebarBackground: 'black'
  sidebarBackgroundType: GRADIENT
  sidebarShadow: false
  useBackgroundTexture: false
  colors:
    purple: '#7E83C4'
    black: '#444444'
  palette:
    primary: 'PURPLE'
    link: 'PURPLE'
  extraCss:
    - "inline:sidecar.css: .gitter-chat-embed { margin-top: 50px; }"
    - 'assets/css/plugins.scss'
    - 'assets/css/extras.scss'
  extraJs:
    - "inline:sidecar.js:((window.gitter = { }).chat = { }).options = { room: 'JavaEden/Orchid' }; "
    - "https://sidecar.gitter.im/dist/sidecar.v1.js"
    - "assets/js/simpleFilter.js"

services:
  publications:
    stages:
      - type: githubReleases
        repo: 'JavaEden/Orchid'
        commitish: 'master'

allPages:
  components:
    - type: "pageContent"
    - type: "prism"
      githubTheme: 'duotone-light'
      languages:
        - kotlin
        - java
        - groovy
        - yaml
        - asciidoc
        - markdown
